# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'notepad_mainwindowNCXsQW.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(307, 351)
        self.action_N = QAction(MainWindow)
        self.action_N.setObjectName(u"action_N")
        self.action_W = QAction(MainWindow)
        self.action_W.setObjectName(u"action_W")
        self.action_O = QAction(MainWindow)
        self.action_O.setObjectName(u"action_O")
        self.action_S = QAction(MainWindow)
        self.action_S.setObjectName(u"action_S")
        self.action_A = QAction(MainWindow)
        self.action_A.setObjectName(u"action_A")
        self.action_U = QAction(MainWindow)
        self.action_U.setObjectName(u"action_U")
        self.action_P = QAction(MainWindow)
        self.action_P.setObjectName(u"action_P")
        self.action_X = QAction(MainWindow)
        self.action_X.setObjectName(u"action_X")
        self.action_S_2 = QAction(MainWindow)
        self.action_S_2.setObjectName(u"action_S_2")
        self.action_S_2.setCheckable(True)
        self.action_U_2 = QAction(MainWindow)
        self.action_U_2.setObjectName(u"action_U_2")
        self.action_T = QAction(MainWindow)
        self.action_T.setObjectName(u"action_T")
        self.action_C = QAction(MainWindow)
        self.action_C.setObjectName(u"action_C")
        self.action_P_2 = QAction(MainWindow)
        self.action_P_2.setObjectName(u"action_P_2")
        self.action_L = QAction(MainWindow)
        self.action_L.setObjectName(u"action_L")
        self.actionBing_S = QAction(MainWindow)
        self.actionBing_S.setObjectName(u"actionBing_S")
        self.action_F = QAction(MainWindow)
        self.action_F.setObjectName(u"action_F")
        self.action_N_2 = QAction(MainWindow)
        self.action_N_2.setObjectName(u"action_N_2")
        self.action_V = QAction(MainWindow)
        self.action_V.setObjectName(u"action_V")
        self.action_R = QAction(MainWindow)
        self.action_R.setObjectName(u"action_R")
        self.action_G = QAction(MainWindow)
        self.action_G.setObjectName(u"action_G")
        self.action_A_2 = QAction(MainWindow)
        self.action_A_2.setObjectName(u"action_A_2")
        self.action_D = QAction(MainWindow)
        self.action_D.setObjectName(u"action_D")
        self.action_W_2 = QAction(MainWindow)
        self.action_W_2.setObjectName(u"action_W_2")
        self.action_F_2 = QAction(MainWindow)
        self.action_F_2.setObjectName(u"action_F_2")
        self.action_I = QAction(MainWindow)
        self.action_I.setObjectName(u"action_I")
        self.action_O_2 = QAction(MainWindow)
        self.action_O_2.setObjectName(u"action_O_2")
        self.action_7 = QAction(MainWindow)
        self.action_7.setObjectName(u"action_7")
        self.action_H = QAction(MainWindow)
        self.action_H.setObjectName(u"action_H")
        self.action_F_3 = QAction(MainWindow)
        self.action_F_3.setObjectName(u"action_F_3")
        self.action_A_3 = QAction(MainWindow)
        self.action_A_3.setObjectName(u"action_A_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")

        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 307, 22))
        self.menu_F = QMenu(self.menubar)
        self.menu_F.setObjectName(u"menu_F")
        self.menu_E = QMenu(self.menubar)
        self.menu_E.setObjectName(u"menu_E")
        self.menu_O = QMenu(self.menubar)
        self.menu_O.setObjectName(u"menu_O")
        self.menu_V = QMenu(self.menubar)
        self.menu_V.setObjectName(u"menu_V")
        self.menu = QMenu(self.menu_V)
        self.menu.setObjectName(u"menu")
        self.menu_H = QMenu(self.menubar)
        self.menu_H.setObjectName(u"menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.menubar.addAction(self.menu_V.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menu_F.addAction(self.action_N)
        self.menu_F.addAction(self.action_W)
        self.menu_F.addAction(self.action_O)
        self.menu_F.addAction(self.action_S)
        self.menu_F.addAction(self.action_A)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_U)
        self.menu_F.addAction(self.action_P)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_X)
        self.menu_E.addAction(self.action_U_2)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_T)
        self.menu_E.addAction(self.action_C)
        self.menu_E.addAction(self.action_P_2)
        self.menu_E.addAction(self.action_L)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actionBing_S)
        self.menu_E.addAction(self.action_F)
        self.menu_E.addAction(self.action_N_2)
        self.menu_E.addAction(self.action_V)
        self.menu_E.addAction(self.action_R)
        self.menu_E.addAction(self.action_G)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_A_2)
        self.menu_E.addAction(self.action_D)
        self.menu_O.addAction(self.action_W_2)
        self.menu_O.addAction(self.action_F_2)
        self.menu_V.addAction(self.menu.menuAction())
        self.menu_V.addAction(self.action_S_2)
        self.menu.addAction(self.action_I)
        self.menu.addAction(self.action_O_2)
        self.menu.addAction(self.action_7)
        self.menu_H.addAction(self.action_H)
        self.menu_H.addAction(self.action_F_3)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.action_A_3)

        self.retranslateUi(MainWindow)
        self.action_X.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_N.setText(QCoreApplication.translate("MainWindow", u"New File(&N)", None))
        self.action_W.setText(QCoreApplication.translate("MainWindow", u"New Window(&W)", None))
        self.action_O.setText(QCoreApplication.translate("MainWindow", u"Open(&O)...", None))
        self.action_S.setText(QCoreApplication.translate("MainWindow", u"Save(&S)", None))
        self.action_A.setText(QCoreApplication.translate("MainWindow", u"Save as a new(&A)...", None))
        self.action_U.setText(QCoreApplication.translate("MainWindow", u"Page Setting(&U)...", None))
        self.action_P.setText(QCoreApplication.translate("MainWindow", u"Print(&P)...", None))
        self.action_X.setText(QCoreApplication.translate("MainWindow", u"Exit(&X)", None))
        self.action_S_2.setText(QCoreApplication.translate("MainWindow", u"Status bar(&S)", None))
        self.action_U_2.setText(QCoreApplication.translate("MainWindow", u"Undo(&U)", None))
        self.action_T.setText(QCoreApplication.translate("MainWindow", u"Cut(&T)", None))
        self.action_C.setText(QCoreApplication.translate("MainWindow", u"Copy(&C)", None))
        self.action_P_2.setText(QCoreApplication.translate("MainWindow", u"Paste(&P)", None))
        self.action_L.setText(QCoreApplication.translate("MainWindow", u"Delete(&L)", None))
        self.actionBing_S.setText(QCoreApplication.translate("MainWindow", u"Search in Bing(&S)...", None))
        self.action_F.setText(QCoreApplication.translate("MainWindow", u"Find(&F)...", None))
        self.action_N_2.setText(QCoreApplication.translate("MainWindow", u"Find next(&N)", None))
        self.action_V.setText(QCoreApplication.translate("MainWindow", u"Find privious(&V)", None))
        self.action_R.setText(QCoreApplication.translate("MainWindow", u"Change(&R)...", None))
        self.action_G.setText(QCoreApplication.translate("MainWindow", u"Move(&G)...", None))
        self.action_A_2.setText(QCoreApplication.translate("MainWindow", u"Select all(&A)", None))
        self.action_D.setText(QCoreApplication.translate("MainWindow", u"Time/Date(&D)", None))
        self.action_W_2.setText(QCoreApplication.translate("MainWindow", u"Auto Line Change(&W)", None))
        self.action_F_2.setText(QCoreApplication.translate("MainWindow", u"Font(&F)...", None))
        self.action_I.setText(QCoreApplication.translate("MainWindow", u"Zoom in(&I)", None))
        self.action_O_2.setText(QCoreApplication.translate("MainWindow", u"Zoom out(&O)", None))
        self.action_7.setText(QCoreApplication.translate("MainWindow", u"Zoom defult", None))
        self.action_H.setText(QCoreApplication.translate("MainWindow", u"View help(&H)", None))
        self.action_F_3.setText(QCoreApplication.translate("MainWindow", u"Send Feedback(&F)", None))
        self.action_A_3.setText(QCoreApplication.translate("MainWindow", u"About Notepad(&A)", None))
        self.menu_F.setTitle(QCoreApplication.translate("MainWindow", u"File(&F)", None))
        self.menu_E.setTitle(QCoreApplication.translate("MainWindow", u"Edit(&E)", None))
        self.menu_O.setTitle(QCoreApplication.translate("MainWindow", u"Format(&O)", None))
        self.menu_V.setTitle(QCoreApplication.translate("MainWindow", u"View(&V)", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"Zoom In/Zoom Out", None))
        self.menu_H.setTitle(QCoreApplication.translate("MainWindow", u"Help(&H)", None))
    # retranslateUi

